version: "3.8"
services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: todos
      TZ: Asia/Tokyo
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: